version: '3.8'

services:
  prayer-scraper:
    image: prayertimes:latest
    container_name: prayer-scraper
    ports:
      - "5002:5002"
    environment:
      - CITY_ID=1
    restart: unless-stopped